// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/orpharion/go-excelAPI/pkg/object

// Package object implements a request data model for excel workbooks.
// Todo ZERO vs NIL??
// We use the zero-value to return all values, and the nil pointer to ignore.
package object
